board_app_creator/urls.py
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from board_app_creator import models, views

urlpatterns = [
    url(r'^/*$', views.index, name='index'),
    url(r'^social_auth/', include('social.apps.django_app.urls', namespace='social')),
    url(r'^logout/', 'django.contrib.auth.views.logout', {'template_name': 'board_app_creator/logout.html'}, name='logout'),
    url(r'^application/?$', views.ApplicationList.as_view(queryset=models.Application.objects.all_real()), name='application-list'),
    url(r'^application/create/?$', login_required(views.ApplicationCreate.as_view()), name='application-create'),
    url(r'^application/hidden/?$', views.ApplicationList.as_view(), name='application-hidden'),
    url(r'^application/(?P<pk>\d+)/?$', views.ApplicationDetail.as_view(), name='application-detail'),
    url(r'^application/(?P<pk>\d+)/delete/?$', login_required(views.ApplicationDelete.as_view()), name='application-delete'),
    url(r'^application/(?P<pk>\d+)/ignore/?$', login_required(views.application_toggle_no_application), name='application-ignore'),
    url(r'^application/(?P<pk>\d+)/renew/?$', login_required(views.application_update_from_makefile), name='application-renew'),
    url(r'^application/(?P<pk>\d+)/update/?$', login_required(views.ApplicationUpdate.as_view()), name='application-update'),
    url(r'^board/?$', views.BoardList.as_view(queryset=models.Board.objects.all_real()), name='board-list'),
    url(r'^board/create/?$', login_required(views.BoardCreate.as_view()), name='board-create'),
    url(r'^board/hidden/?$', views.BoardList.as_view(), name='board-hidden'),
    url(r'^board/(?P<pk>\d+)/?$', views.BoardDetail.as_view(), name='board-detail'),
    url(r'^board/(?P<pk>\d+)/delete/?$', login_required(views.BoardDelete.as_view()), name='board-delete'),
    url(r'^board/(?P<pk>\d+)/ignore/?$', login_required(views.board_toggle_no_board), name='board-ignore'),
    url(r'^board/(?P<pk>\d+)/update/?$', login_required(views.BoardUpdate.as_view()), name='board-update'),
    url(r'^job/?$', views.JobList.as_view(queryset=models.Job.objects.select_subclasses()), name='job-list'),
    url(r'^job/create/?$', login_required(views.JobCreate.as_view()), name='job-create'),
    url(r'^job/create_appjob/?$', login_required(views.ApplicationJobCreate.as_view()), name='application-job-create'),
    url(r'^job/renew/?$', login_required(views.job_update_all), name='job-renew-all'),
    url(r'^job/update_appjob/(?P<board>[^/]+)/(?P<application>[^/]+)/?$', login_required(views.job_update_from_board_app), name='job-update-from-board-app'),
    url(r'^job/(?P<pk>\d+)/?$', views.JobDetail.as_view(), name='job-detail'),
    url(r'^job/(?P<pk>\d+)/delete/?$', login_required(views.JobDelete.as_view()), name='job-delete'),
    url(r'^job/(?P<pk>\d+)/renew/?$', login_required(views.job_update), name='job-renew'),
    url(r'^job/(?P<pk>\d+)/update/?$', login_required(views.JobUpdate.as_view()), name='job-update'),
    url(r'^job/(?P<pk>\d+)/update_appjob/?$', login_required(views.ApplicationJobUpdate.as_view()), name='application-job-update'),
    url(r'^repository/?$', views.RepositoryList.as_view(), name='repository-list'),
    url(r'^repository/create/?$', login_required(views.RepositoryCreate.as_view()), name='repository-create'),
    url(r'^repository/(?P<pk>\d+)/?$', views.RepositoryDetail.as_view(), name='repository-detail'),
    url(r'^repository/(?P<pk>\d+)/add_application_trees/$', login_required(views.RepositoryAddApplicationTrees.as_view()), name='repository-add-application-trees'),
    url(r'^repository/(?P<pk>\d+)/delete/?$', login_required(views.RepositoryDelete.as_view()), name='repository-delete'),
    url(r'^repository/(?P<pk>\d+)/renew/?$', login_required(views.repository_update_applications_and_boards), name='repository-renew'),
    url(r'^repository/(?P<pk>\d+)/update/?$', login_required(views.RepositoryUpdate.as_view()), name='repository-update'),
]

riot_job_manager/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'riot_job_manager.views.home', name='home'),
    url(r'^jobs/', include('board_app_creator.urls')),
)

board_app_creator/models.py
"""
Models for board_app_creator application.
"""
import re
from os import listdir
from os.path import join as path_join, relpath

from django.conf import settings
from django.core.exceptions import ValidationError
from django.db import models
from django.db.models.signals import pre_save, post_save

from model_utils.managers import InheritanceManager

import board_app_creator.validators as validators
import vcs
import usb
import jenkins.jobs

class RepositoryManager(models.Manager):
    """
    Model manager for Repository
    """
    def get_or_create_from_path(self, path):
        """
        Get or create a repo from path
        """
        vcs_repo = vcs.get_repository(path)
        return self.get_or_create(url=vcs_repo.url, path=vcs_repo.directory)

    def get_or_create_from_url(self, url, vcs_type='git'):
        """
        Get or create a repo from URL
        """
        if url[-4:] == ".git":
            directory = re.sub(r'^.*/([^/]+)\.git$', r'\1', url)
        else:
            directory = re.sub(r'^.*/([^/]+)$', r'\1', url)
        path = path_join(settings.RIOT_REPO_BASE_PATH, directory)
        vcs_repo = vcs.get_repository(path, url=url, vcs=vcs_type)
        return self.get_or_create(url=vcs_repo.url,
                                  path=relpath(vcs_repo.directory,
                                               settings.RIOT_REPO_BASE_PATH))

class USBDeviceManager(models.Manager):
    """
    Model manager for USBDevice
    """
    def update_from_system(self):
        """
        Get all currently connected USB devices and update data base
        accordingly
        """
        Port.objects.update(usb_device=None)
        for dev in usb.get_device_list():
            device, _ = self.get_or_create(usb_id=dev.usb_id, tag=dev.tag)
            try:
                port = Port.objects.get(path=dev.device)
                port.usb_device = device
            except Port.DoesNotExist:
                port = Port(path=dev.device)
            port.save()

class BoardManager(models.Manager):
    """
    Model manager for Board
    """
    def all_real(self):
        """
        All boards that do not have the no_board flag set.
        """
        return self.filter(no_board=False)

    def hidden_shown(self):
        return self.filter(no_board=True).exists()

class ApplicationManager(models.Manager):
    """
    Model manager for Application
    """
    def all_real(self):
        """
        All applications that do not have the no_application flag set.
        """
        return self.filter(no_application=False)

    def hidden_shown(self):
        return self.filter(no_application=True).exists()

class Repository(models.Model):
    """
    A RIOT related repository
    """
    url = models.CharField(max_length=256, verbose_name="URL", unique=True,
                           blank=False, null=False,
                           validators=[validators.validate_git_repository])
    path = models.CharField(max_length=256, unique=True)
    default_branch = models.CharField(max_length=32, blank=False, null=False,
                                      default='master')
    vcs = models.CharField(max_length=8, choices=[('git', 'Git')], blank=False,
                           null=False, default='git', verbose_name="VCS")
    has_boards_tree = models.BooleanField(default=False, null=False,
                                       verbose_name="Has Boards tree")
    boards_tree = models.CharField(max_length=256, default=None, null=True,
                                   blank=True)
    has_cpu_tree = models.BooleanField(default=False, null=False,
                                       verbose_name="Has CPU tree")
    cpu_tree = models.CharField(max_length=256, default=None, null=True,
                                blank=True, verbose_name="CPU tree")
    is_default = models.BooleanField(default=False, null=False)

    objects = RepositoryManager()

    class Meta:
        ordering = ['-is_default', 'path']

    def __str__(self):
        return self.url

    def save(self, *args, **kwargs):
        if self.is_default:
            qs = Repository.objects.filter(is_default=True)
            if self.pk != None:
                qs = qs.exclude(pk=self.pk)
            if qs.exists():
                self.is_default = True
        super(Repository, self).save(*args, **kwargs)

    @models.permalink
    def get_absolute_url(self):
        return ('repository-detail', (self.pk,))

    @property
    def vcs_repo(self):
        """
        Object representing the actual repository
        """
        if not hasattr(self, '_vcs'):
            self._vcs = vcs.get_repository(
                    path_join(settings.RIOT_REPO_BASE_PATH, self.path),
                    self.vcs, self.url)
        return self._vcs

    @property
    def weblink(self):
        """
        Tries to parse weblink from URL or returns None
        """
        ssh_guess = re.match(r"(?P<username>[a-z_][a-z0-9_]+)@(?P<hostname>[^:]+):(?P<path>.+)", self.url)
        if ssh_guess == None:
            m = re.match(r"(?P<schema>[a-zA-Z,+-0-9]+)://(?P<hostname>[^/]+)/(?P<path>.+)", self.url)
        else:
            m = ssh_guess

        if m.group('hostname') != "github.com":
            return None

        path = m.group('path')
        path = re.sub(r'(.*)\.git/*', r'\1', path)

        return "https://{}/{}".format(m.group('hostname'), path)

    def has_application_trees(self):
        return self.application_trees.exists()

    def unique_application_trees(self):
        return sorted(list(set(self.application_trees.values_list('tree_name', flat=True))))

    def update_boards(self):
        for tree in self.vcs_repo.head.get_file(self.boards_tree).trees:
            board, created = Board.objects.get_or_create(riot_name=tree.name)

            if not board.no_board:
                path = path_join(self.boards_tree, tree.name)
                board.path = path
                board.repo = self
                try:
                    board.cpu_repo = Repository.objects.get(is_default=True)
                except Repository.DoesNotExist:
                    pass
                board.save()

    def update_applications(self):
        for tree_name in self.unique_application_trees():
            for app in self.vcs_repo.head.get_file(tree_name).trees:
                abs_path = path_join(tree_name, app.name)
                makefile = path_join(abs_path, 'Makefile')
                try:
                    app_name, blacklist, whitelist = Application.get_name_and_lists_from_makefile(self, makefile)
                except Application.DoesNotExist:
                    continue
                except AssertionError:
                    continue
                appobj, created = Application.objects.get_or_create(name=app_name,
                                                                    path=abs_path)
                if created or not appobj.no_application:
                    app_tree, created = ApplicationTree.objects.get_or_create(
                        tree_name=tree_name, repo=self, application=appobj)
                    for board in Board.objects.all():
                        if board.riot_name in blacklist and board not in appobj.blacklisted_boards.all():
                            appobj.blacklisted_boards.add(board)
                        if board.riot_name in whitelist and board not in appobj.blacklisted_boards.all():
                            appobj.whitelisted_boards.add(board)

class USBDevice(models.Model):
    """
    Representation of USB devices.
    """
    tag = models.CharField(max_length=60, blank=True, null=True)
    usb_id = models.CharField(max_length=9, blank=False, null=False,
                              unique=True)

    objects = USBDeviceManager()

    def __str__(self):
        connected = " [{}]".format(
                ', '.join([str(p) for p in self.ports.all()]) \
                     if self.ports.exists() else " [not connected]")
        if self.tag:
            return "{} ({}){}".format(self.usb_id, self.tag, connected)
        else:
            return "{}{}".format(self.usb_id)

class Port(models.Model):
    """
    Ports a board is connected on to this system.
    """
    path = models.CharField(max_length=20, unique=True, blank=False, null=False)
    usb_device = models.ForeignKey('USBDevice', related_name='ports', blank=True,
                                   null=True)

    def __str__(self):
        return self.path

class Board(models.Model):
    """
    A board in one of the RIOT repositories.
    """
    riot_name = models.CharField(max_length=16, unique=True, blank=False,
                                 null=False, db_index=True,
                                 verbose_name="RIOT name")
    repo = models.ForeignKey('Repository', related_name='boards',
                             limit_choices_to={'has_boards_tree': True},
                             verbose_name='repository', blank=True, null=True)
    cpu_repo = models.ForeignKey('Repository', related_name='cpus',
                                 limit_choices_to={'has_cpu_tree': True},
                                 verbose_name='CPU Repository', blank=True,
                                 null=True)
    usb_device= models.OneToOneField('USBDevice', related_name='board',
                                     blank=True, null=True,
                                     verbose_name="USB Device")
    prototype_jobs = models.ManyToManyField('ApplicationJob',
                                            related_name='board_prototype_for', 
                                            blank=True)
    no_board = models.BooleanField(default=False, blank=False, null=False,
                                   editable=False)

    objects = BoardManager()

    class Meta:
        ordering = ['riot_name']

    def __str__(self):
        return self.riot_name

    @models.permalink
    def get_absolute_url(self):

board_app_creator/templates/board_app_creator/application_detail.html
{% extends 'board_app_creator/detail.html' %}
{% load bootstrap3 %}
{% block title %}Application: {{ object.name }}{% endblock %}
{% block nav-application-class %}active{% endblock %}
{% block nav-application-link %}#{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url "application-list" %}">Applications</a></li>
    <li active="active">{{ object.name }}</li>
{% endblock %}
{% block header %}Application <small>{{ object.name }}</small>{% endblock %}
{% block actionbar %}
        <a href="{% url "application-update" pk=object.pk %}" title="Edit">{% bootstrap_icon "pencil" %}</a>
        {% if object.no_application %}
            <a href="{% url "application-ignore" pk=object.pk %}" title="Handle as application">{% bootstrap_icon "eye-open" %}</a>
        {% else %}
            <a href="{% url "application-ignore" pk=object.pk %}" title="Do not handle as application">
                {% bootstrap_icon "eye-close" %}
            </a>
        {% endif %}
        <a href="{% url "application-renew" pk=object.pk %}" title="Reload application">{% bootstrap_icon "refresh" %}</a>
        <a href="{% url "application-delete" pk=object.pk %}" title="Delete" class="text-danger">{% bootstrap_icon "remove" %}</a>
{% endblock %}
{% block detail %}
    {% if object.repository.exists %}
    <dt>Repository</dt>
    {% for r in object.repository.all %}
    <dd><a href="{% url "repository-detail" pk=r.pk %}">{{ r }}</a></dd>
    {% endfor %}
    {% endif %}
    <dt>Path</dt>
    <dd>{{ object.path }}</dd>
    {% if object.blacklisted_boards.exists %}
    <dt>Blacklisted boards</dt>
    {% for b in object.blacklisted_boards.all %}
    <dd><a href="{% url "board-detail" pk=b.pk %}">{{ b }}</a></dd>
    {% endfor %}
    {% endif %}
    {% if object.whitelisted_boards.exists %}
    <dt>Whitelisted boards</dt>
    {% for b in object.whitelisted_boards.all %}
    <dd><a href="{% url "board-detail" pk=b.pk %}">{{ b }}</a></dd>
    {% endfor %}
    {% endif %}
{% endblock %}

board_app_creator/templates/board_app_creator/application_form.html
{% extends 'board_app_creator/form.html' %}
{% load bootstrap3 %}
{% block title %}{{ form_verb }} Application{% endblock %}
{% block nav-application-class %}active{% endblock %}
{% block nav-application-link %}#{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url "application-list" %}">Applications</a></li>
    <li active="active">{{ form_verb }} Applictation</li>
{% endblock %}
{% block header %}{{ form_verb }} Application{% endblock %}
{% block submit_text %}{% if form_verb == "Add" %}{% bootstrap_icon "plus" %}{% else %}{% bootstrap_icon "pencil" %}{% endif %} {{ form_verb }}{% endblock %}

board_app_creator/templates/board_app_creator/application_list.html
{% extends 'board_app_creator/list.html' %}
{% load bootstrap3 %}
{% block title %}Applications{% endblock %}
{% block nav-application-class %}active{% endblock %}
{% block nav-application-link %}#{% endblock %}
{% block header %}Applications <small><a class="btn btn-success" href="{% url "application-create" %}">{% bootstrap_icon "plus" %} Add application</a></small>{% endblock %}
{% block list-table-head %}
    <th>Name</th>
    <th>Repository</th>
    <th>Path</th>
    <th>Prototype jobs</th>
    <th></th>
    <th>
        {% if hidden_shown %}
            <a href="{% url "application-list" %}" title="Do not show hidden" class="text-muted">{% bootstrap_icon "eye-close" %}</a>
        {% else %}
            <a href="{% url "application-hidden" %}" title="Show hidden" class="text-muted">{% bootstrap_icon "eye-open" %}</a>
        {% endif %}
    </th>
    <th></th>
    <th></th>
{% endblock %}
{% block list-table-row %}
    <tr class="{% if object.no_application %}danger{% endif %}">
        <td><a href="{{ object.get_absolute_url }}">{{ object.name }}</a></td>
        <td>
            {% for repo in object.repository.all %}
                <a href="{{ object.get_absolute_url }}">{{ repo }}</a>{% if not forloop.last %},{% endif %}
            {% empty %}
                &mdash;
            {% endfor %}
        </td>
        <td>{{ object.path }}</td>
        <td>{% if object.prototype_jobs %}{{ object.prototype_jobs.all|join:", "|default:"&mdash;"}}{% else %}&mdash;{% endif %}</td>
        <td><a href="{% url "application-update" pk=object.pk %}" title="Edit" class="text-muted">{% bootstrap_icon "pencil" %}</a></td>
        <td>
            {% if object.no_application %}
                <a href="{% url "application-ignore" pk=object.pk %}" title="Handle as application" class="text-muted">
                    {% bootstrap_icon "eye-open" %}
                </a>
            {% else %}
                <a href="{% url "application-ignore" pk=object.pk %}" title="Do not handle as application" class="text-muted">
                    {% bootstrap_icon "eye-close" %}
                </a>
            {% endif %}
        </td>
        <td><a href="{% url "application-renew" pk=object.pk %}" title="Reload application" class="text-muted">{% bootstrap_icon "refresh" %}</a></td>
        <td><a href="{% url "application-delete" pk=object.pk %}" title="Delete" class="text-danger">{% bootstrap_icon "remove" %}</a></td>
    </tr>
{% endblock %}
{% block list-table-empty %}
    No applications found. <a href="{% url "application-create" %}">Add one</a>
{% endblock %}

board_app_creator/templates/board_app_creator/board_confirm_delete.html
{% extends 'board_app_creator/base.html' %}
{% load bootstrap3 %}
{% block title %}Delete Board{% endblock %}
{% block nav-board-class %}active{% endblock %}
{% block nav-board-link %}#{% endblock %}
{% block header %}Delete Board {{ object.path }}{% endblock %}
{% block content %}
    <form action="#" method="post" class="form">
        {% csrf_token %}
        Delete Board {{ object.name }}?
        {% buttons %}
            <button type="submit" class="btn btn-success">
                Yes
            </button>
            <a href="{{ view.get_success_url }}" class="btn btn-danger">
                No
            </a>
        {% endbuttons %}
    </form>
{% endblock %}

board_app_creator/templates/board_app_creator/board_detail.html
{% extends 'board_app_creator/detail.html' %}
{% load bootstrap3 %}
{% block title %}Board: {{ object.riot_name }}{% endblock %}
{% block nav-board-class %}active{% endblock %}
{% block nav-board-link %}#{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url "board-list" %}">Boards</a></li>
    <li active="active">{{ object.riot_name }}</li>
{% endblock %}
{% block header %}Board <small>{{ object.riot_name }}</small>{% endblock %}
{% block actionbar %}
    <a href="{% url "board-update" pk=object.pk %}" title="Edit">{% bootstrap_icon "pencil" %}</a>
    {% if object.no_board %}
        <a href="{% url "board-ignore" pk=object.pk %}" title="Handle as board">{% bootstrap_icon "eye-open" %}</a>
    {% else %}
        <a href="{% url "board-ignore" pk=object.pk %}" title="Do not handle as board">{% bootstrap_icon "eye-close" %}</a>
    {% endif %}
    <a href="{% url "board-delete" pk=object.pk %}" title="Delete" class="text-danger">{% bootstrap_icon "remove" %}</a>
{% endblock %}
{% block detail %}
    <dt>Repository</dt>
    <dd>{{ object.repo }}</dd>
    <dt>CPU Repository</dt>
    <dd>{{ object.cpu_repo }}</dd>
    {% if object.usb_device %}
    <dt>USB Device</dt>
    <dd>{{ object.usb_device }}</dd>
    {% endif %}
    {% if object.prototype_jobs.objects.exists %}
    <dt>Prototype jobs</dt>
    {% for t in object.application_trees.all %}
    <dd>{{ t }}</dd>
    {% endfor %}
    {% endif %}
{% endblock %}

board_app_creator/templates/board_app_creator/board_form.html
{% extends 'board_app_creator/form.html' %}
{% load bootstrap3 %}
{% block title %}{{ form_verb }} Board{% endblock %}
{% block nav-board-class %}active{% endblock %}
{% block nav-board-link %}#{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url "board-list" %}">Boards</a></li>
    <li active="active">{{ form_verb }} Board</li>
{% endblock %}
{% block header %}{{ form_verb }} Board{% endblock %}
{% block submit_text %}{% if form_verb == "Add" %}{% bootstrap_icon "plus" %}{% else %}{% bootstrap_icon "pencil" %}{% endif %} {{ form_verb }}{% endblock %}

board_app_creator/templates/board_app_creator/board_list.html
{% extends 'board_app_creator/list.html' %}
{% load bootstrap3 %}
{% block title %}Boards{% endblock %}
{% block nav-board-class %}active{% endblock %}
{% block nav-board-link %}#{% endblock %}
{% block header %}Boards <small><a class="btn btn-success" href="{% url "board-create" %}">{% bootstrap_icon "plus" %} Add board</a></small>{% endblock %}
{% block list-table-head %}
    <th>RIOT name</th>
    <th>Repository</th>
    <th>CPU Repository</th>
    <th>USB Device</th>
    <th>Prototype jobs</th>
    <th></th>
    <th>
        {% if hidden_shown %}
            <a href="{% url "board-list" %}" title="Do not show hidden" class="text-muted">{% bootstrap_icon "eye-close" %}</a>
        {% else %}
            <a href="{% url "board-hidden" %}" title="Show hidden" class="text-muted">{% bootstrap_icon "eye-open" %}</a>
        {% endif %}
    </th>
    <th></th>
{% endblock %}
{% block list-table-row %}
    <tr class="{% if object.no_board %}danger{% endif %}">
        <td><a href="{{ object.get_absolute_url }}">{{ object.riot_name }}</a></td>
        <td><a href="{{ object.repo.get_absolute_url }}">{{ object.repo }}</a></td>
        <td><a href="{{ object.cpu_repo.get_absolute_url }}">{% if object.cpu_repo %}{{ object.cpu_repo }}{% else %}&mdash;{% endif %}</a></td>
        <td>{% if object.usb_device %}{{ object.usb_device }}{% else %}&mdash;{% endif %}</td>
        <td>{% if object.prototype_jobs %}{{ object.prototype_jobs.all|join:", "|default:"&mdash;"}}{% else %}&mdash;{% endif %}</td>
        <td><a href="{% url "board-update" pk=object.pk %}" title="Edit" class="text-muted">{% bootstrap_icon "pencil" %}</a></td>
        <td>
            {% if object.no_board %}
                <a href="{% url "board-ignore" pk=object.pk %}" title="Handle as board" class="text-muted">
                    {% bootstrap_icon "eye-open" %}
                </a>
            {% else %}
                <a href="{% url "board-ignore" pk=object.pk %}" title="Do not handle as board" class="text-muted">
                    {% bootstrap_icon "eye-close" %}
                </a>
            {% endif %}
        </td>
        <td><a href="{% url "board-delete" pk=object.pk %}" title="Delete" class="text-danger">{% bootstrap_icon "remove" %}</a></td>
    </tr>
{% endblock %}
{% block list-table-empty %}
    No boards found. <a href="{% url "board-create" %}">Add one</a>
{% endblock %}

board_app_creator/templates/board_app_creator/form.html
{% extends "board_app_creator/base.html" %}
{% load bootstrap3 %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
            {% block breadcrumb %}{% endblock %}
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="#" method="post" class="form">
                {% csrf_token %}
                {% bootstrap_form form %}
                <div class="form-group">
                    {% block extra_text %}{% endblock %}
                </div>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% block submit_text %}{% endblock %}
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

board_app_creator/templates/board_app_creator/job_confirm_delete.html
{% extends 'board_app_creator/base.html' %}
{% load bootstrap3 %}
{% block title %}Delete Job: {{ object.name }}{% endblock %}
{% block nav-application-class %}active{% endblock %}
{% block nav-application-link %}#{% endblock %}
{% block header %}Delete Job {{ object.name }}{% endblock %}
{% block content %}
    <form action="#" method="post" class="form">
        {% csrf_token %}
        Delete Job {{ object.name }}?
        {% buttons %}
            <button type="submit" class="btn btn-success">
                Yes
            </button>
            <a href="{{ view.get_success_url }}" class="btn btn-danger">
                No
            </a>
        {% endbuttons %}
    </form>
{% endblock %}

board_app_creator/templates/board_app_creator/job_prototype_form.html
{% extends 'board_app_creator/job_form.html' %}
{% load bootstrap3 %}
{% block title %}{{ form_verb }} Job{% endblock %}
{% block nav-job-class %}active{% endblock %}
{% block nav-job-link %}#{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-md-12">
            <ol class="breadcrumb">
            {% block breadcrumb %}{% endblock %}
            </ol>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <form action="#" method="post" class="form">
                {% csrf_token %}
                {{ formset.forms.0.fields.name }}
                {% bootstrap_formset formset %}
                <div class="form-group">
                    {% block extra_text %}{% endblock %}
                </div>
                {% buttons %}
                    <button type="submit" class="btn btn-primary">
                        {% block submit_text %}{% endblock %}
                    </button>
                {% endbuttons %}
            </form>
        </div>
    </div>
{% endblock %}

board_app_creator/templates/board_app_creator/logout.html
{% extends 'board_app_creator/base.html' %}
{% load bootstrap3 %}
{% block title %}{{ title }}{% endblock %}
{% block header %}{{ title }}{% endblock %}

board_app_creator/templates/board_app_creator/repository_add_application_trees.html
{% extends "board_app_creator/form.html" %}
{% load bootstrap3 %}
{% block title %}{{ object.get_vcs_display }} repository: {{ object.url }} (Edit application trees){% endblock %}
{% block header %}Edit application trees of {{ object.get_vcs_display }} repository <small>{{ object.url }}</small>{% endblock %}
{% block breadcrumb %}
    <li><a href="{% url "repository-list" %}">Repositories</a></li>
    <li><a href="{{ object.get_absolute_url }}">{{ object.path }}</a></li>
    <li active="active">Edit application trees</li>
{% endblock %}
{% block submit_text %}{% bootstrap_icon "save" %} Save{% endblock %}